from . import chamada
from . import provincia
from . import distrito
from . import categoria
from . import subcategoria
from . import caso
from . import caso_categoria
from . import caso_subcategoria
from . import case_type_classification
from . import knowledgebase
from . import person_involved
from . import moz_learning
from . import moz_learning_complaint_details
from . import gender_based_violence
from . import deficiente
from . import asterisk
from . import popup
